ALTER TABLE menu
ADD COLUMN IF NOT EXISTS is_eggless BOOLEAN DEFAULT FALSE;

ALTER TABLE menu
ADD COLUMN IF NOT EXISTS ingredients TEXT;

ALTER TABLE menu
ADD COLUMN IF NOT EXISTS allergens TEXT;

ALTER TABLE menu
ADD COLUMN IF NOT EXISTS is_today_special BOOLEAN DEFAULT FALSE;

ALTER TABLE menu
ADD COLUMN IF NOT EXISTS special_date DATE;
